### ISSUE TITLE
POAM Update Process

### ISSUE THREAD

**Issue by amilash** [raft-tech/TANF-app#1185]
Need a process to update the POAMS with scan findings
Need:
- cadence for review
- place to update
- place to house POAMs docs
- person responsible for updating
- way to check for this (is there an automated way of doing this)?

AC:
- this should be guided by our ATO requirements so that we are fulfilling them

**Comment by ADPennington** [comment]
@lfrohlich @amilash notes below --

- **re: cadence for review** these are reviewed as part of every PR, but the most reliable scans we currently have to inform POAM updates run against the deployed site nightly. The monthly reports that will be generated when #1161 is addressed should be aligned with the nightly scan and can be used  for POAM update purposes. 

- **re: way to check for this** related to the above. re: monthly scan generation, these should go through normal gitflow process, to ensure everyone has seen these prior to updating POAM. 

- **re: person responsible for updating** I'll take lead on POAM updates. 

- **re: place to update + place to house POAM doc** the template for POAM (copied from [here](https://hhsgov.sharepoint.com/:x:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/System%20Security%20Plan/TANF-POAM-2021.xlsx?d=w375c3e5f052b40c9a2cb8ed752362cbc&csf=1&web=1&e=6IcTjZ)) below. We could keep something like this in the repo with monthly scan reports but should also still maintain a physical doc in SharePoint that can be included in ATO package:

| Program Office | System/Project Name | OCIO POC |
|--|--|--|
| Office of Family Assistance (OFA)  | TANF Data Portal (TDP) | Email: Penyin.Asare@acf.hhs.gov; Github: `PenyinAsare`|


|System Name    (1) | Weakness Source Name   (2) | Weakness ID    (3) | Weakness Description    (4)  | Weakness Source Document Date    (5) | Submission Date   (6) | Weakness Source Type    (7) | Risk Level   (8) | Primary Control related to the Weakness    (9) | Security Control Family    (10) | Submitted by   Point of Contact    (11) | Submitted by   POC Title    (12) | Scheduled Completion Date   (14) | Milestones with Completion Dates   (15) | Status   (16) | Comments   (17)|
|-- | -- | -- | --------- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --|
|TDP | Owasp-zap vulnerability scan | [WASC-15](http://projects.webappsec.org/w/page/13246914/Application%20Misconfiguration) |[Content Security Policy (CSP) Header Not Set.](https://9263-281707402-gh.circle-artifacts.com/0/tdrs-frontend/reports/owasp_report.html#10038)  |  5/7/2021 | 5/7/2021 | Vulnerability Scan | 3) Moderate |   | Configuration Management (CM) | Alex Pennington | OFA TDP Tech Lead | 5/31/2021 |   | Open |  CSP is an added layer of security that helps to detect/mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. [XSS](https://csrc.nist.gov/glossary/term/Cross_site_Scripting) is a vulnerability that allows attackers to inject malicious code into an otherwise benign website. [Data injection](https://owasp.org/www-community/Injection_Theory) is when an attacker’s attempt to send data to an application in a way that will change the meaning of commands being sent to an interpreter. **_We created a ticket (https://github.com/raft-tech/TANF-app/issues/907) to address this and will address post-ATO_**.|

**Comment by lfrohlich** [comment]
Closed as Alex's comment fulfilled it. Also copied into [OneNote](https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/_layouts/OneNote.aspx?id=%2Fsites%2FTANFDataPortalOFA%2FSiteAssets%2FTANF%20Data%20Portal%20%28OFA%29%20Notebook&wd=target%28Compliance.one%7CD9B65AB8-BF29-476A-A652-D003714E50A4%2FPOAM%20Update%20process%7C92C1711C-958D-4228-8C9C-FA26E33D3878%2F%29
onenote:https://hhsgov.sharepoint.com/sites/TANFDataPortalOFA/SiteAssets/TANF%20Data%20Portal%20(OFA)%20Notebook/Compliance.one#POAM%20Update%20process&section-id={D9B65AB8-BF29-476A-A652-D003714E50A4}&page-id={92C1711C-958D-4228-8C9C-FA26E33D3878}&end)
