### ISSUE TITLE
Update workflow.md

### ISSUE THREAD

**Issue by lfrohlich** [raft-tech/TANF-app#1482]
@ADPennington working on first --> @abottoms-coder --> @reitermb --> @valcollignon --> @lfrohlich
#1382 PR

HackMD: https://hackmd.io/@valeriecollignon/HJKO_E1IF/edit

**Comment by ADPennington** [comment]
handed off to @abottoms-coder on 12/8, with following comments:
- this document could be much shorter. Main sections of markdown could be:
  - New issue is created
  - New issue is refined, pointed, and brought into sprint
  - Issue is started. Include sub-bullets on what happens when issue gets blocked or grows in scope. 
  - Issue is ready for raft review 
  - Issue is ready for gov review. 
  - Issue is ready to close. 

- doc would benefit from leading with a brief, high-level summary of feature development process from research>design>dev>hhs:main (DoD). 
- Where possible include links to relevant docs like tabletop ADR, dependabot ADR, etc. 
- It should also be clear when things like a11y review is incorporated into raft review (e.g. frontend-related issues should always consider if a11y review should an AC)

**Comment by abottoms-coder** [comment]
Made some minor edits, added many comments but wanted to get some real-time feedback before making major alterations. Passing to @reitermb

**Comment by ADPennington** [comment]
> Made some minor edits, added many comments but wanted to get some real-time feedback before making major alterations. Passing to @reitermb

reviewed and responded.

**Comment by reitermb** [comment]
Reviewed, added comments, also holding off on making edits prior to the potential follow-on session. Passing on to @valcollignon!

**Comment by valcollignon** [comment]
Reviewed and added comments. Ready for @lfrohlich :)

**Comment by abottoms-coder** [comment]
Happy Monday, @lfrohlich -- what is the status of this? Happy to setup a meeting for you for consensus building on this.

**Comment by valcollignon** [comment]
@ADPennington to work on and Raft team to review before holidays 12/23.

**Comment by valcollignon** [comment]
[section on gov priorities](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/team-charter/our-workflow.md#government-priorities) will be moved to [our team and values](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/team-charter/our-team-and-values.md) per workflow sync 12.23.21
CC: @sreedevip @reitermb @ADPennington

**Comment by valcollignon** [comment]
@sreedevip to work on workflow diagram with @ADPennington and @reitermb over the holidays. Updates to be made in this issues and in Mattermost to keep the team informed async. Once diagram is completed, @ADPennington will create a pull request to finalize the workflow documentation.
Per workflow sync 12.23.21
CC: @lfrohlich
