### ISSUE TITLE
[Design] Change Account Requests

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#1662]
**Description**
Stub ticket to close out #1001 and potentially be mapped to a TDP release (post V3). Can be refined to deliver design spec for change request management in TDP.

**Relevant notes from #1001**

Current change process:
1. User sends email to sys admin or sys owner to request change to their TDP access (e.g. change in group permissions, account deactivation, account reactivation ~~[note: users also currently have the ability to change their own STT via the profile page, which is the same as the request access page])~~ (Note no longer applicable as of #1496)
2. Sys admin or sys owner approves changes via email.
3. Sys admin implements changes via user profiles.
4. Sys admin notifies user of changes via email.

Concerns about this process:
- Change requests submitted externally from TDP or users have the ability to change their STT by navigating to profile page (either is problematic).
- Parts of the change approval process take place externally from TDP
- Same issues documented in #1001 re: approval process (Extra-TDP systems, difficult verification process to confirm legitimacy of approval/changes, current lack of notifications)

**UX Notes**
- #1495 has solved for the potential issue originally noted in the current change process of users being able to change their own STT indefinitely. 
- The regional staff UI doesn't currently include any method or workflow for regional staff to _edit_ user data (Name, email, STT), however as the designs need to be updated for other reasons (changes to roles since the original designs, as well as some a11y improvements - #203) we could examine potential ways to solve the above concerns in parallel to that work. 
- If we productize this process we'll need both regional UI screens and likely an update to the user profile page
   - As a grantee user I need a mechanism on my profile page to let me submit changes to my associated STT or Name to a regional staff admin for approval.
   - As a regional staff admin I need a queue of change requests to approve or deny in TDP's admin UI.
- Questions around whether we need additional measures to validate information given to us by grantees probably fall under the research scope of #214 
- The full list of prospective tasks below probably represents more than one ticket

**Prospective Tasks:**
- [ ] Review current admin screens/flows and discuss merits of including change requests in the same queue as access requests (possibly changing the name in the process) or whether it's better to have separate queues for Access and Change requests respectively.
   - [ ] Re-task/spin out additional tickets accordingly based on decisions here
- [ ] Draft testable mockups in Figma
- [ ] Test design with DIGIT & Regional OFA folks
- [ ] Review testing results, make appropriate changes
- [ ] Finalize as dev-ready design

**Research Questions**

**Comment by ADPennington** [comment]
adding notes from [this comment](https://github.com/raft-tech/TANF-app/issues/1387#issuecomment-1022606603) for consideration:

Changes to a user's role or affiliation seem unlikely based on current practices, but there are some edge cases (noted below) that could be investigated and accounted for in a later release (v4+).

-  Users belonging to a federal permissions groups (i.e. those that begin with "OFA"):
   - do not need an STT assignment, and it is not expected that this will ever change.
   - their region affiliation could potentially change, especially in the scenario where they are affiliated with multiple regions. More research is needed to understand what functions they need (e.g. access to reports within their region(s) only?)

- Users belonging to a non-federal group:
  - may need an STT assignment change, but it seems unlikely if they are maintaining the same email address since most users will have an email address that includes the STT name (e.g. [someone@dc.gov](mailto:someone@dc.gov)). In this scenario, we'd probably want to deactivate their old STT account and activate their new STT account. An exception might be vendor staff ([someone@deloitte.com](mailto:someone@deloitte.com)) who could theoretically move from one STT agency to another -- this seems like an edge case but another topic for research. Another edge case is when a user is submitting data on behalf of multiple STTs (e.g. state and a tribe). This can likely be resolved with onboarding training, but we will defer to research.
  - when an STT does change for a user, the region should already be accounted for dynamically based on the [STTs model](https://tdp-backend-staging.app.cloud.gov/admin/stts/stt/2898/change/)
- At some point, we're going to need a change request form for existing users to ask for a change in their account status, affiliation, or role. Most common scenario will likely be deactivation. Currently, for TDRS, the person requesting deactivation is usually also the person requesting activation for someone else's new account, but since TDP requires account setup first for new requests, the change request flow for TDP deactivation may require divorcing these two requests. Another research topic.

**Comment by lfrohlich** [comment]
Need to investigate whether some tribes share individual contractors who submit data on their behalf

**Comment by reitermb** [comment]
Closing this as mostly outdated post onboarding efforts but will discuss in #2910 to confirm there are no up-to-date related needs for admin-ing in Django.
