### ISSUE TITLE
Create mockups for responsive version of the app to view on my phone/tablet

### ISSUE THREAD

**Issue by reitermb** [raft-tech/TANF-app#178]
Description:
Create mockups to ensure all patterns are responsive. Mockups created for closed issues - #7 and #8 . 

Problem Statement:
If a user wants to look at the site as a half window a responsive site must be made.
If a user wants to look at the site on their mobile device or tablet, a responsive site must be made.

AC: 
- [x] The problem we are trying to solve is clearly stated, as are questions we still have 
- [x] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [x] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [x] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [x] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, ) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 

Tasks
- [x] Design mockups for tablet/phone sizes for all existing screens that don't yet have them
- [x] Check for accessibility 

Open Questions
- [x] Bottom nav or top bar menu?
- [x] Is there filtering for Users on mobile?

Commit Link
Figma : https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=618%3A14

DD
- [x] Documentation: Design has been shared with the PO and team for feedback
- [ ] @cmajel has reviewed and signed off
- [ ] @lfrohlich has reviewed and signed off

**Comment by cmajel** [comment]
As a note, [USWDS components](https://designsystem.digital.gov/components/) and [default layouts](https://designsystem.digital.gov/page-templates/) are responsive by default, so this might be a good opportunity to pair with a dev to see how much design guidance is needed.

**Comment by dk-ui** [comment]
@lfrohlich @cmajel Review : Screens that require mockups for responsive design behavior are shown in the Figma link below. Some of these screens might change slightly depending on their desktop counterparts however they do serve the purpose of giving the devs insight into responsive behavior of new non USWDS design components.

Figma Link : https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-Admin-Mockups-For-Feedback?node-id=0%3A1

**Comment by dk-ui** [comment]
@shubhi-raft Accessibility for bottom nav corrected. Ticket placed in Raft Review.

**Comment by dk-ui** [comment]
@shubhi-raft Took out screens pertaining to #164 and #166. The screens left should represent legacy screens from #7 and #8

**Comment by shubhi-raft** [comment]
Thanks @dk-ui ! 

@cmajel @lfrohlich ready for your review.

**Comment by dk-ui** [comment]
@lfrohlich @cmajel Problem statement / reason for this ticket and questions we still have are documented within Figma for this ticket.

**Comment by cmajel** [comment]
@dk-ui can you add the problem statement and open questions to the ticket header so that it's easier to track back later?

@reitermb @dk-ui, summarizing the feedback in figma:
* The mobile footer bar (like apps often have) is a non standard USWDS pattern. I'd recommend we use the standard header component that flexes down to a header flyout ([demo](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.8.1/components/preview/header--basic.html) | [docs](https://designsystem.digital.gov/components/header/))
* There is some inconsistent behavior in what got included in the mobile top header and what gets included in the mobile footer bar - switching to one menu via flyout could also help remedy that.
* I'm not sure what this icon is for and why it appears on mobile - can you say more?
<img width="400" alt="Screen Shot 2020-08-31 at 5 45 47 PM" src="https://user-images.githubusercontent.com/2374206/91771911-d300b880-ebb1-11ea-92c4-cb36953e1413.png">
* Similarly, I'm not sure what the `Filter` dropdown on the user tables accomplishes - is this something we need for MVP?
* Noting that login.gov's mobile styles are hosted by them, so that won't require work on our end. 

If these changes are made I'm ok demoing and signing off.

**Comment by lfrohlich** [comment]
@dk-ui  @reitermb  can you confirm when@cmajel 's comments have been addressed so this can be closed? Thanks!

**Comment by dk-ui** [comment]
@lfrohlich all comments have been addressed. Two tickets were created #208 and #207

**Comment by lfrohlich** [comment]
Great, thanks! Closing this issue.
