### ISSUE TITLE
Add GitHub badges 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#187]
Description: Add Github badges to readme. Note, this we need this done for the heuristics 18F is creating for Lauren.

AC:
 - [x] All badges are visible and working

Tasks:
 - [x] Dev team connect with @lauraGgit to confirm these are the right badges
 - [ ] Removing Snyk from circleci as [orbs](https://circleci.com/docs/2.0/orb-intro/) aren't supported in HHS repo
 - [ ] Configure Snyk to scan the public Github  Raft-fork (@RafterGit)
 - [ ] Configure Snyk to scan the HHS fork (@lauraGgit)

For the Raft fork, the following badges will be added:
   - [x] Add badges for API: Build, Coverage, Security
   - [x] Add badges for Frontend: Build, Coverage, Security 

For the HHS fork, the following badges will be added
   - [x] Add badges for API: Build, Coverage, Security 
   - [x] Add badges for Frontend: Build, Coverage, Security

**Comment by lfrohlich** [comment]
@lauragGit can you confirm whether these are the right badges?

**Comment by RafterGit** [comment]
After a  conversation with @lauraGgit:

The HHS repo does not support [CircleCi Orbs](https://circleci.com/docs/2.0/orb-intro/). In response to this, the CircleCI test automation that executes Snyk vulnerability scanning [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/.circleci/config.yml#L31-L34) will have to be removed due to its use of the [Snyk orb](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/.circleci/config.yml#L149-L150).

Snyk vulnerability scans will be conducted via the [Snyk Github Integration](https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration).

The new security badges will be derived from this integration.

**Comment by lfrohlich** [comment]
This is complete- badges are operational
