### ISSUE TITLE
[bug] `Newest` filter in search_indexes not working in staging environment

### ISSUE THREAD

**Issue by ADPennington** [raft-tech/TANF-app#2885]
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

When submitting files with parsable records in staging environment (currently on sprint 93 release), the records in the database cannot be found by using the `newest` filter. 

## Action Taken

- uploaded a file with one record that can be parsed
- navigated to `frontend/admin/search_indexes` to relevant schema and observed that newest record parsed is not tagged as "newest"

## What I expected to see

https://github.com/raft-tech/TANF-app/assets/63075587/cb8ab9fc-4137-4f72-8156-a4752c70699e

## What I did see

https://github.com/raft-tech/TANF-app/assets/63075587/39e65ea3-9bba-4458-82a5-e26214f1fd57

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

* If record has no datafile assigned, orders at top
* possibly also caused by elastic instance being unavailable, parsed records would have been reverted
* investigate logs

## Acceptance Criteria
* [ ] Investigate failure, determine path forward

**Comment by elipe17** [comment]
@ADPennington I was able to reproduce this issue in staging but am unable outside of it. However, I did discover the issue. In the staging DB there are records that have their datafile set as a `None`. This causes a problem because the `newest` filter determines the newest records based on the datafile's ID. Because there are records without a datafile, Django is defaulting their non-existent datafile.id to be larger (newer) than any other record. Really the best way to resolve this issue is to remove the records without an associated datafile from the DB. These records were likely added to the DB before [this PR](https://github.com/raft-tech/TANF-app/pull/2607) was merged. The linked PR is what added the datafile relation to the records. Let me know your thoughts!

**Comment by ADPennington** [comment]
@elipe17  thank you. @jtimpe suggested that this was probably the case. i can remove those records if you can share the command to do so.

**Comment by elipe17** [comment]
@ADPennington sure thing. From the backend `shell_plus` you can run the following commands.

```python
TANF_T1.objects.filter(datafile=None).delete()
TANF_T2.objects.filter(datafile=None).delete()
TANF_T3.objects.filter(datafile=None).delete()
SSP_M1.objects.filter(datafile=None).delete()
SSP_M2.objects.filter(datafile=None).delete()
SSP_M3.objects.filter(datafile=None).delete()
```

**Comment by ADPennington** [comment]
@elipe17 I completed this task today.
