### ISSUE TITLE
Create ADR for Anti-virus strategy

### ISSUE THREAD

**Issue by kniz-raft** [raft-tech/TANF-app#699]
Based on the recommendation John put in the comments and OCIO's consent, we will be going forward with checking to make sure all uploaded files are a text file, which cannot contain viruses. The ADR should include how we are determining the file type.

AC:

- [x] ADR is documented in code docs
- [ ] System Security Plan is updated
- [ ] Update Boundary Diagram

For reference: https://csrc.nist.gov/Projects/risk-management/sp800-53-controls/release-search#!/control?version=5.1&number=SI-3

**Comment by kniz-raft** [comment]
@jtwillis92 I assigned this to you since it sounded like you might have a few leads to explore here. If you could refine the ticket so we can review it next time we meet, that would be awesome - thank you!

**Comment by jtwillis92** [comment]
A few considerations:
* If we only allow uploading `.txt` files *and* assert that the files are valid `.txt` based on the file headers then those files by nature cannot have viruses.
* Since the upload to S3 is done directly from the client using Signed URLs we won't have a way to intercept the file before it gets to S3 without putting a proxy in place in front of S3 (not recommended)
* Furthermore, since the backend never actually sees the file it cannot assert the file type as expected.
* Scanning this file to assert the correct file type on the frontend would not be recommended as it would be easy for a bad actor to circumvent this behavior client side.
* S3 does support virus scans along with quarantining files that are determined to be malicious.
* Without removing signed URLs and altering the upload flow such that the file is uploaded to our backend and then posted to S3 we have limited means to scan the file before it gets to S3

That being said, the path of least resistance going forward seems to be scanning the file directly in S3 via a lambda function or something similar. [Here](https://aws.amazon.com/marketplace/pp/widdix-GmbH-VirusScan-for-Amazon-S3/B07XFR781T) is an example of an AWS Marketplace item that accomplishes this task. (Note: this is not free)

Additionally, we could go the route of building it ourselves - as outlined in [this blog](https://engineering.upside.com/s3-antivirus-scanning-with-lambda-and-clamav-7d33f9c5092e)

**Comment by kniz-raft** [comment]
We'll ask OCIO at IPT about only accepting .txt files/appropriate headers

**Comment by alexsoble** [comment]
A file scanning option from the OHS TTA project that we could potentially reuse: https://github.com/HHS/Head-Start-clamav-api-cg-app/

Summary: "This project aims to create a deployable cloud.gov app that will expose a REST api for scanning files for malware with ClamAV."

Configured to deploy to Cloud.gov. An option to consider! cc @kniz-raft @jtwillis92 @carltonsmith

**Comment by lfrohlich** [comment]
OCIO said this should be sufficient as long as it is documented in an ADR and control (SI-3)

**Comment by kniz-raft** [comment]
@jtwillis92 This story has been updated to capture the work of documenting an ADR

**Comment by kniz-raft** [comment]
Alex S will update the SSP based on a request from OCIO (after this was originally closed). Boundary diagram updates are not needed as part of this.

**Comment by alexsoble** [comment]
@kniz-raft Done! 😄
