### ISSUE TITLE
Create design components for login screen 

### ISSUE THREAD

**Issue by shubhi-raft** [raft-tech/TANF-app#7]
Mockup the components of the login screen and placeholder page. 
 
AC:
- [ ] Login meets the https://designsystem.digital.gov/
- [x] Login screen has a login button and some notification to tell user about redirect to login.gov
- [x] Mockup a placeholder page with a placeholder welcome message

DoD
- [x] Documentation: Design has been shared with the PO and team for feedback

**Comment by lfrohlich** [comment]
Should this be a task under a user story as opposed to its own issue?

**Comment by shubhi-raft** [comment]
Could be. However, something to think about is - if it is included within a user story then the estimated story point will increase and it may bigger than we are hoping. 

Having a separate issue but tied/reference  to the bigger issue may be easier way to keep track.

**Comment by shubhi-raft** [comment]
Also, how does the QASP apply for design for DoD (or does it?)>?

@lfrohlich QASP states 

> Research plans and artifacts from usability testing and/or other research methods with end users are available at the end of every applicable sprint, in accordance with the contractor’s research plan.

we tried to frame DOD around this QASP. feel free to edit.

**Comment by reitermb** [comment]
Update to capture a conversation we had among the Raft team, our current understanding is that the only part of the login flow that lives in the TDP application will be a sort of landing page for logging in rather than the form itself. That latter part of the flow lives on the login.gov side of things and upon successful authentication would then redirect back to the TDP app. 

![image](https://user-images.githubusercontent.com/28515874/88557107-cd82e200-cff7-11ea-8316-f77a0cccc069.png)

**Comment by cmajel** [comment]
@reitermb that's correct. Here are some examples of sites that use login.gov if you want to see how others have approach it:
* https://openforest.fs.usda.gov/ (via `sign in with login.gov to apply`)
* https://www.usajobs.gov/ (via `sign in`)
* https://ttp.cbp.dhs.gov/ (via `log in`)

**Comment by shubhi-raft** [comment]
@reitermb ACF's digital toolbox - https://www.acf.hhs.gov/digital-toolbox/visuals/templates

**Comment by lfrohlich** [comment]
@shubhi-raft  the DoD and keeping this as an issue make sense to me. Thanks

**Comment by reitermb** [comment]
https://www.figma.com/file/y954oTPUK7ZOvXuhI0oA9b/Login-Flow?node-id=0%3A1
Link to mockups---Ready for review @lfrohlich

**Comment by reitermb** [comment]
An open question regarding tweaks around "branding", is the eventual TDP something that should use the full ACF/OFA logotype (as seen here https://www.acf.hhs.gov/digital-toolbox/visuals/logos) or something else?

**Comment by shubhi-raft** [comment]
@adamcaron - could you also take a look at the figma link to make sure the mockups look good?

**Comment by cmajel** [comment]
So exciting to see things coming together 🎉 🎉 

I took a look had some feedback/questions I wanted to get down:

About interaction / content
* I like that we're adding in the ACF logo and colors. [The bottom of this page on the toolkit](https://www.acf.hhs.gov/digital-toolbox/visuals/logos) mentions they aren't accepting new brands, which we should investigate further. I'd recommend we add a more descriptive placeholder, like "TANF data reporting system", to this so it's clearer that your logging into an app, rather than ACF. 
* The login.gov guidance recommends having [a clear sign out option](https://partners.login.gov/guides/sign-in-guidelines/), which is missing.
* I see under users there are options to filter by `STTs` and `Select type for STTs`. Can you say more how these could work (select box vs something else) and the kinds of things someone could do with them? What `types` do we think would live here?
* It's not clear how someone in the admin view would get from the role overview to a specific role like data prepper. Are these table rows meant to be clickable?
* Also, it can be helpful to number or label the screens so that it's easier to talk about / reference them. 

About UI
*  I'd double check if the text to background color contrast is accessible for the grey tables on the user and roles administration pages; they look a little low contrast to me. [I use this checker](https://webaim.org/resources/contrastchecker/) but Figma may have a plugin you can use too.
* I see some alignment shifts between the gov banner, header and main content. USWDS does have [a grid system](https://designsystem.digital.gov/utilities/layout-grid/), which I find is easiest to conceptualize from looking at the guides they give in [their sketch assets](https://designsystem.digital.gov/documentation/designers/) (not sure about their figma assets) or from [their demo pages](https://designsystem.digital.gov/page-templates/).

**Comment by reitermb** [comment]
@cmajel Thanks for the super quick feedback! I really appreciate it! 

- Some of our questions were on the branding front as well, OFA is one of the current brands on their list (office brands seem to simply be a matter of changing the sub-heading on the logotype), but given the internal / TANF centric focus of this tool we weren't sure exactly how that does or should affect things here. e.g. What's required and what might be expected by various users.
- Thanks for the login.gov guidance resource! For the purposes of this first "Hello World-y" sprint, I've made it a part of the element highlighting user role, but we'd anticipate it'll end up in a more traditional header area location sooner rather than later—really as soon as we take a pass on IA and nail down some non-placeholder header-content a little bit more.
- Re: Admin screens, I should have clarified that those aren't quite ready for prime time yet like the login ones—They were just at the resolution of some mid-conversation wireframing to help us better frame a technical discussion about how user management will work with login.gov and what—if any—constraints come with that. 
Our (very) early thinking regarding filtering though was that STTs and User Role could both make sense as filtering categories. The control itself was based on one used in the [HMDA Data Browser](https://ffiec.cfpb.gov/data-browser/data/2019?category=counties) if you'd like to take a look at a functional one! 
- Something I was curious about was whether there are any examples to turn to of USDWS being used in admin interfaces (or in any more highly interactive ones outside the context of admin-ing.) From clickable (to sort) columns in tables to elements with view vs edit states. It seems there's plenty of room to add functionalities onto it if/when they're needed, but it's always helpful to get a look at any precedent if it's out there!

**Comment by shubhi-raft** [comment]
@cmajel @lfrohlich https://www.figma.com/file/y954oTPUK7ZOvXuhI0oA9b/Login-Flow?node-id=0%3A1 updated with some of the comments above.

**Comment by lfrohlich** [comment]
Exciting stuff! Looks like a good start. A few initial thoughts: 

I can ask ACF comms about policy around logo for a system like this now or at a later point. For examples of other ACF websites see https://pathwaystowork.acf.hhs.gov/ and https://childcare.gov/ and https://peerta.acf.hhs.gov/. What about something like the breadcrumbs/pathway on PeerTA and Pathways to Work clearinghouse could be good in addition to the footer. Thoughts? 

Would the user be taken to the TDP before they get sent to login.gov and then back to the TDP? Or would it be ACF/OFA website >> Login.gov >> TDP? I ask because the ACF/OFA website isn't technically the app in the pathway. I like the inclusion of the link on the OFA website.  

I think the "sign out" button makes sense in the top right under your user name.

**Comment by shubhi-raft** [comment]
> What about something like the breadcrumbs/pathway on PeerTA and Pathways to Work clearinghouse could be good in addition to the footer. Thoughts?

Good suggestion! The suggestions you provided seem to be off a website and not necessarily of an app. For the website/i.e., where the user first lands to use the app (before they click on sign in w/ login.gov), [breadcrumbs exist](https://user-images.githubusercontent.com/22622384/89450197-2ead6280-d728-11ea-81d1-69a6d7c80fc2.png). This may not exactly be the place where the app lives but we have it here to provide a frame of reference. We can add the breadcrumbs in the app itself, though it may lead to confusion if we create breadcrumbs for the app itself (i.e., the user is nested on some section of the app). Thoughts?
> 
> Would the user be taken to the TDP before they get sent to login.gov and then back to the TDP? Or would it be ACF/OFA website >> Login.gov >> TDP? I ask because the ACF/OFA website isn't technically the app in the pathway. I like the inclusion of the link on the OFA website.

If the link to TDP app is included within the OFA website, then a user will need to be sign in w/ login.gov before they see the TDP app. so what you stated here is correct - ACF/OFA website >> Login.gov >> TDP [Login.gov flow](https://user-images.githubusercontent.com/22622384/89450740-06723380-d729-11ea-87a7-5ab3360349e5.png)

> I think the "sign out" button makes sense in the top right under your user name.
Yes, sign out will be available underneath the chevron on the top right. mockup updated to show the what this would look like. 

@lfrohlich

**Comment by cmajel** [comment]
@reitermb @shubhi-raft took a look at this:

* for `placeholder page w/ link to TDP login`, I believe that login.gov requires the log in process to initiate from the app that you're logging into. So, you wouldn't be able to log into TDP from the ACF homepage; you'd need to log in to a TDP homepage / url.  @lauraGgit or maybe @carltonsmith could confirm. 

* I believe this footer is meant to be a placeholder? I'd expect it to be more centered around content about the OFA data team more than than ACF-wide programs and contacts. If it is a placeholder maybe we just limit it to the ACF logo for now. 

* Liking the dropdown in the header to manage log in / profile!

* Small UI thing: I see we're using Public Sans, whereas the [ACF typography docs](https://www.acf.hhs.gov/digital-toolbox/visuals/typography-and-fonts) use different sans serifs: Arial, Calibri, Helvetica Neue, Source Sans Pro. Can you say more about this choice?

**Comment by reitermb** [comment]
@cmajel 

> for `placeholder page w/ link to TDP login`, I believe that login.gov requires the log in process to initiate from the app that you're logging into. So, you wouldn't be able to log into TDP from the ACF homepage; you'd need to log in to a TDP homepage / url. 

Great callout! We dug into this a little this afternoon and that would seem to be right. Sounds like there _might_ be a way around it if we really needed it, but it's probably not something we need to invest time into when we can more easily create a dedicated TDP landing page. 

> I believe this footer is meant to be a placeholder? I'd expect it to be more centered around content about the OFA data team more than than ACF-wide programs and contacts. If it is a placeholder maybe we just limit it to the ACF logo for now.

Yep, just a placeholder at the moment, I've gone ahead and cut it down to just being ACF/OFA centric. 

> Small UI thing: I see we're using Public Sans, whereas the [ACF typography docs](https://www.acf.hhs.gov/digital-toolbox/visuals/typography-and-fonts) use different sans serifs: Arial, Calibri, Helvetica Neue, Source Sans Pro. Can you say more about this choice?

Public Sans (though I do love it in all of its neutral, open-source glory) was more a byproduct of having plugged into USDWS assets than a design choice. I've been converting things over to the ACF Typography guidelines, and it should all be in accordance with those soon!

**Comment by cmajel** [comment]
@reitermb @shubhi-raft added comments via figma on the updated login wires:
https://www.figma.com/file/irgQPLTrajxCXNiYBTEnMV/Login-%2F-Admin-Mockups-For-Feedback?node-id=0%3A1

**Comment by reitermb** [comment]
@cmajel @lfrohlich These should be ready for review as well as #8 screens! As noted there, I think we've hit on all the feedback, but just let me know if anything was overlooked!

**Comment by cmajel** [comment]
🎉  Awesome looks good to me!

**Comment by lfrohlich** [comment]
Looks good to me too--thanks!
